- name: Target Machine (Ubunt 20.04) Update [ apt update]
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install Nginx into Target Machine ( apt install nginx )
  apt:
    name: nginx
    state: latest
- name: Ansible copy certs directory to the remote server
  copy:
    src: certs
    dest: "{{NGINX_HOME}}/conf.d"
    owner: "{{ NGINX_USER }}"
    group: "{{ NGINX_USER }}"
    mode: 0775
- name: Ansible copy SSL conf to the remote server
  template:
    src: ssl.conf.j2
    dest: "{{NGINX_HOME}}/conf.d/ssl.conf"
    owner: "{{ NGINX_USER }}"
    group: "{{ NGINX_USER }}"
    mode: 0664

- name: Ansible copy default conf to the remote server
  template:
    src: default.conf.j2
    dest: "{{NGINX_HOME}}/sites-available/default"
    owner: "{{ NGINX_USER }}"
    group: "{{ NGINX_USER }}"
    mode: 0664

- name: Copy Application Content to Root Directory
  copy:
    src: web
    dest: "{{CONTENT_ROOT}}/"
    owner: "{{ NGINX_USER }}"
    group: "{{ NGINX_USER }}"
    mode: 0775



