- name: Target Machine (Ubunt 20.04) Update [ apt update]
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install Nginx into Target Machine ( apt install nginx )
  apt:
    name: nginx
    state: latest


